name: rl_vin
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib[version='>=2.0.0']
  - numpy[version='>=1.12.1']
  - scipy[version='>=0.19.0']
  - torchvision[version='>=0.1.8']
  - conda-forge::tqdm
